version: 2
updates:
  # Enable version updates for Python pip packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "chatbet-team"
    assignees:
      - "chatbet-team"
    commit-message:
      prefix: "deps:"
      include: "scope"
    labels:
      - "dependencies"
      - "python"

  # Enable security updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "chatbet-team"
    assignees:
      - "chatbet-team"
    commit-message:
      prefix: "security:"
      include: "scope"
    labels:
      - "security"
      - "dependencies"